arb-dir: lib/core/localization/l10n
template-arb-file: app_en.arb
output-dir: lib/core/localization/generated 
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [en, es]
synthetic-package: false